.TH HANGMAN 1 "May 2023" "Version 1.0" "User Commands"

.SH NAME
hangman \- starts the Hangman game

.SH SYNOPSIS
hangman [OPTIONS]... \-starts the Hangman game with choosen option

.SH DESCRIPTION
Hangman is a classic word-guessing game that challenges players to uncover a hidden word before running out of attempts. It tests vocabulary and deductive skills.

.PP
.B Gameplay:
.nf
The Hangman game is played by following these steps:
1. The Hangman game is launched.
2. The number of players is chosen, and unique nicknames are assigned.
3. Letters are guessed one by one to uncover the hidden word.
4. The part of hangman is drawn for each incorrect guess.
5. Points are earned based on correctly guessed letters.
6. The game ends, when hangman is completed or word is guessed.
7. The winner is determined as the player with the highest score.
.ef

.PP
.B Word themes:
.nf
Online mode contains:
-proverbs, 
-movies, 
-countries and capitals.
Players can choose their preferred theme for an added variety. 
Offline mode contains:
-a pre-loaded file containing animals names is available,
-option to create personalized word file with custom passwords.
.ef

.SH OPTIONS
.TP
-h
Output a usage message and exit.

.TP
-v
Output version number and author data.

.SH AUTHOR
Weronika Koterba, 193127

.SH REPORTING BUGS
Email bug reports to s193127@student.pg.edu.pl.

.SH COPYRIGHT
Copyright General Public License

.SH SEE ALSO
Email questions to s193127@student.pg.edu.pl for more information.
